name: Collect ubuntu browser dependencies
on:
    schedule:
        - cron: 0 0 1 * *
permissions:
    pull-requests: write
jobs:
    collect:
        name: Collect browser dependencies
        runs-on: ${{ matrix.os }}
        env:
            BRANCH_NAME: resolve-ubuntu-dependencies-${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GH_ACCESS_TOKEN }}
            - name: Setup Node JS
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org
            - run: sudo apt-get update
            - run: sudo apt-get install -y apt-file
            - run: sudo apt-file update
            - run: npm ci
            - run: git config --global user.email "y-infra@yandex.ru"
            - run: git config --global user.name "y-infra"
            - run: git checkout -b ${{ env.BRANCH_NAME }}
            - run: npm run resolve-ubuntu-dependencies
            - name: Commit changes
              run: |
                  git add src && \
                  git commit src -m 'chore: update local browser dependencies for ${{ matrix.os }}' && \
                  git push origin ${{ env.BRANCH_NAME }} && \
                  gh pr create -B master -H ${{ env.BRANCH_NAME }} --title "Auto update local browser deps for ${{ matrix.os }}" --body "Created by Github action" || echo "No changes"
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
